# Generated by Django 5.2.5 on 2025-10-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cesnet_service_path_plugin', '0026_segment_segment_type_segment_type_specific_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='provider_segment_contract',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='provider_segment_name',
        ),
    ]
