# Generated by Django 5.2.7 on 2025-11-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cesnet_service_path_plugin', '0033_contractinfo_contractsegmentmapping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractinfo',
            name='provider',
        ),
    ]
