# Generated by Django 5.2.7 on 2025-12-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesnet_service_path_plugin', '0034_remove_contractinfo_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractinfo',
            name='number_of_recurring_charges',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractinfo',
            name='recurring_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contractinfo',
            name='recurring_charge_period',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
