# Custom migration: switch primary key from segment_id to auto-generated id
# for DarkFiberSegmentData, EthernetServiceSegmentData, OpticalSpectrumSegmentData.
#
# Django's auto-generated migration fails because it tries to add a new PK
# column while the old PK constraint still exists. This migration uses raw SQL
# to do the steps in the correct order:
#   1. Drop the existing PK constraint on segment_id
#   2. Add a new "id" identity column as the primary key
#   3. Add a UNIQUE constraint on segment_id (required by OneToOneField)
#   4. Register the state changes so Django's ORM stays in sync

import django.db.models.deletion
from django.db import migrations, models


# (table_name, old_pkey_constraint_name)
# Constraint names come from the \d output in Postgres.
TABLES = [
    (
        "cesnet_service_path_plugin_darkfibersegmentdata",
        "cesnet_service_path_plugin_darkfibersegmentdata_pkey",
    ),
    (
        "cesnet_service_path_plugin_ethernetservicesegmentdata",
        "cesnet_service_path_plugin_ethernetservicesegmentdata_pkey",
    ),
    (
        "cesnet_service_path_plugin_opticalspectrumsegmentdata",
        "cesnet_service_path_plugin_opticalspectrumsegmentdata_pkey",
    ),
]


def forwards(apps, schema_editor):
    for table, pkey_name in TABLES:
        # 1. Drop the existing primary key (segment_id)
        schema_editor.execute(f'ALTER TABLE "{table}" DROP CONSTRAINT "{pkey_name}";')
        # 2. Add new "id" column as identity primary key
        schema_editor.execute(
            f'ALTER TABLE "{table}" ADD COLUMN "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;'
        )
        # 3. Add unique constraint on segment_id (OneToOneField needs it)
        schema_editor.execute(f'ALTER TABLE "{table}" ADD CONSTRAINT "{table}_segment_id_key" UNIQUE ("segment_id");')


def backwards(apps, schema_editor):
    for table, pkey_name in TABLES:
        # Reverse: drop the unique constraint, drop id column, re-add old PK
        schema_editor.execute(f'ALTER TABLE "{table}" DROP CONSTRAINT "{table}_segment_id_key";')
        schema_editor.execute(f'ALTER TABLE "{table}" DROP COLUMN "id";')
        schema_editor.execute(f'ALTER TABLE "{table}" ADD CONSTRAINT "{pkey_name}" PRIMARY KEY ("segment_id");')


class Migration(migrations.Migration):
    dependencies = [
        (
            "cesnet_service_path_plugin",
            "0036_alter_opticalspectrumsegmentdata_chromatic_dispersion",
        ),
    ]

    operations = [
        # Raw SQL handles the actual schema change
        migrations.RunPython(forwards, backwards),
        # State-only operations so Django's ORM knows about the new fields
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="darkfibersegmentdata",
                    name="id",
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name="darkfibersegmentdata",
                    name="segment",
                    field=models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dark_fiber_data",
                        to="cesnet_service_path_plugin.segment",
                    ),
                ),
                migrations.AddField(
                    model_name="ethernetservicesegmentdata",
                    name="id",
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name="ethernetservicesegmentdata",
                    name="segment",
                    field=models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ethernet_service_data",
                        to="cesnet_service_path_plugin.segment",
                    ),
                ),
                migrations.AddField(
                    model_name="opticalspectrumsegmentdata",
                    name="id",
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name="opticalspectrumsegmentdata",
                    name="segment",
                    field=models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optical_spectrum_data",
                        to="cesnet_service_path_plugin.segment",
                    ),
                ),
            ],
            database_operations=[],  # Already handled by RunPython above
        ),
    ]
